// Authored explanation from source code, not a runtime execution trace.
export const speculationScenario = {
  root: 'speculation',
  title: 'speculationAccept',
  subtitle: 'Что такое спекуляция',
  task: 'Объяснить смысл спекуляции через происхождение speculationAccept',
  completion: 'Объяснение спекуляции собрано',
  assumptions: 'Маршрут зависимостей объяснения, а не порядок исполнения программы. Рассматривается принятие подсказки в основном интерфейсе, завершённая и незавершённая работа, отмена. Тексты подготовлены по исходному коду; узлы и результаты этого сценария не записываются в Neo4j.',
  nodes: [
    { id:'speculation', title:'onSubmit.speculationAccept', file:'screens/REPL.tsx', line:3142, deps:['handoff','execution','acceptance','cancel'],
      relations: {"handoff":"создаётся в…","execution":"содержит состояние, созданное в…","acceptance":"передаётся в…","cancel":"содержит состояние, отменяемое в…"},
      syntax: {"description":"Параметр функции","parts":[["onSubmit","function"],[".","punctuation"],["speculationAccept","value"]]},
      need:'Что уже произошло к моменту передачи этого объекта и зачем он нужен?',
      result:'Спекуляция здесь — упреждающее выполнение предложенного следующего запроса до его принятия пользователем. Отдельный агент заранее накапливает сообщения и допустимые изменения во временном каталоге. При принятии подсказки speculationAccept передаёт состояние этой работы, накопленную оценку экономии времени и setAppState. onSubmit использует подготовленное: завершённую работу не запускает повторно, незавершённую продолжает обычным запросом. При отмене подготовка отбрасывается.',
      sources:[['screens/REPL.tsx',3392]] },
    { id:'handoff', title:'PromptInput.onSubmit', file:'components/PromptInput/PromptInput.tsx', line:984, deps:['suggestion','state'],
      relations: {"suggestion":"передаёт подсказку, созданную в…","state":"читает…"},
      syntax: {"description":"Локальная функция","parts":[["PromptInput","function"],[".","punctuation"],["onSubmit","function"]]},
      need:'При каких условиях создаётся третий аргумент onSubmit?',
      result:'Если ввод пуст или точно совпадает с подсказкой, подсказка существует, нет изображений и не открыт агент, активная спекуляция принимается. PromptInput отправляет текст подсказки и объект { state: speculation, speculationSessionTimeSavedMs, setAppState }. Это контекст подготовленного выполнения, а не логический флаг. skipReset сохраняет подготовку до её принятия.' },
    { id:'suggestion', title:'executePromptSuggestion', file:'services/PromptSuggestion/promptSuggestion.ts', line:183, deps:[],
      syntax: {"description":"Асинхронная функция","parts":[["executePromptSuggestion","function"]]},
      need:'Какой запрос выполняется заранее?',
      result:'Для repl_main_thread генератор получает подсказку из контекста разговора и сохраняет её в promptSuggestion. Если спекуляция включена и текст непуст, startSpeculation запускается без ожидания. Это предположение о следующем запросе пользователя, а не уже полученное поручение.' },
    { id:'state', title:'AppState.speculation', file:'state/AppStateStore.ts', line:392, deps:[],
      syntax: {"description":"Свойство типа объекта","parts":[["AppState","type"],[".","punctuation"],["speculation","value"]]},
      sources:[['services/PromptSuggestion/speculation.ts',437]],
      need:'Что хранится в state?',
      result:'Активное состояние хранит идентификатор, abort, время старта, ссылки на сообщения, изменённые пути и контекст, счётчик инструментов и boundary. active означает доступную для принятия подготовку: агент мог ещё работать либо уже завершиться; завершённость уточняется по boundary.' },
    { id:'execution', title:'startSpeculation', file:'services/PromptSuggestion/speculation.ts', line:402, deps:['suggestion','isolation','agent'],
      relations: {"suggestion":"запускается из…","isolation":"задаёт обработчик…","agent":"вызывает…"},
      syntax: {"description":"Асинхронная функция","parts":[["startSpeculation","function"]]},
      need:'Чем упреждающее выполнение отличается от показа подсказки?',
      result:'startSpeculation отменяет предыдущую подготовку, создаёт контроллер отмены и временный каталог, сохраняет активное состояние и запускает runForkedAgent с текстом подсказки как пользовательским сообщением. Сообщения накапливаются отдельно; обычная запись transcript выключена. При успешном окончании ставится boundary=complete.' },
    { id:'isolation', title:'canUseTool (startSpeculation)', file:'services/PromptSuggestion/speculation.ts', line:461, deps:[],
      syntax: {"description":"Свойство с функцией-колбэком","parts":[["canUseTool","function"],[" (","punctuation"],["startSpeculation","function"],[")","punctuation"]]},
      need:'Может ли предположение сразу изменить рабочие файлы?',
      result:'Проверка инструментов ограничивает действия: запись требует подходящего режима разрешений, пути записи внутри cwd перенаправляются во временный каталог с копированием исходника. Чтение ранее изменённого файла идёт туда же. Запись вне cwd запрещена. Bash допускается только после проверки read-only; прочие инструменты останавливают подготовку на границе. Это конкретная политика инструментов, а не гарантия полной изоляции процесса.' },
    { id:'agent', title:'runForkedAgent(...)', file:'services/PromptSuggestion/speculation.ts', line:457, deps:[],
      syntax: {"description":"Вызов функции","parts":[["runForkedAgent","function"],["(...)","punctuation"]]},
      need:'Что именно можно переиспользовать?',
      result:'Вызов получает promptMessages и параметры контекста, querySource=speculation, лимит ходов и обработчик onMessage. Сообщения assistant/user складываются в messagesRef; достижение лимита сообщений вызывает отмену. При штатном завершении сохраняются время и расход выходных токенов. В этом маршруте внутренности агента остаются отдельной границей исследования.',
      sources:[['services/PromptSuggestion/speculation.ts',635]] },
    { id:'acceptance', title:'handleSpeculationAccept', file:'services/PromptSuggestion/speculation.ts', line:835, deps:['commit','continuation'],
      relations: {"commit":"вызывает…","continuation":"возвращает значение для…"},
      syntax: {"description":"Асинхронная функция","parts":[["handleSpeculationAccept","function"]]},
      need:'Как подготовка превращается в часть настоящего разговора?',
      result:'Обработчик очищает подсказку, подготавливает сообщения, добавляет пользовательский запрос и принимает подготовку. Затем добавляет очищенные сообщения и обновляет кэш прочитанных файлов. Для незавершённой работы удаляет хвост assistant, чтобы обычный запрос мог продолжить разговор. Ошибка приводит к queryRequired=true.' },
    { id:'commit', title:'acceptSpeculation', file:'services/PromptSuggestion/speculation.ts', line:717, deps:['state','isolation'],
      relations: {"state":"изменяет…","isolation":"применяет изменения, ограниченные…"},
      syntax: {"description":"Асинхронная функция","parts":[["acceptSpeculation","function"]]},
      need:'Когда применяются файлы и что означает сэкономленное время?',
      result:'Принимается только active-состояние. Агент останавливается; если есть очищенные сообщения, изменённые файлы переносятся из временного каталога в рабочий. Каталог удаляется, состояние сбрасывается в idle. timeSavedMs считается от старта до более раннего из принятия и завершения и прибавляется к счётчику сессии. Это оценка времени предварительной работы, а не измеренное сравнение с повторным запуском.' },
    { id:'continuation', title:'queryRequired (onSubmit)', file:'screens/REPL.tsx', line:3394, deps:[],
      syntax: {"description":"Локальная переменная из деструктуризации","parts":[["queryRequired","value"],[" (","punctuation"],["onSubmit","function"],[")","punctuation"]]},
      need:'Запускается ли запрос второй раз?',
      result:'handleSpeculationAccept возвращает queryRequired=!isComplete, где isComplete требует boundary.type=complete. При true onSubmit создаёт новый контроллер и вызывает onQuery для продолжения; затем выходит из ветки принятия. При complete повторный запрос здесь не нужен. Отсутствие boundary или остановка у инструмента не означают завершённый ответ.',
      sources:[['services/PromptSuggestion/speculation.ts',884],['services/PromptSuggestion/speculation.ts',958]] },
    { id:'cancel', title:'abortSpeculation', file:'services/PromptSuggestion/speculation.ts', line:802, deps:[],
      syntax: {"description":"Функция","parts":[["abortSpeculation","function"]]},
      need:'Что происходит, если пользователь не принимает предположение?',
      result:'abortSpeculation для active-состояния отменяет работу, удаляет временный каталог и возвращает idle. Новый старт сначала отменяет предыдущую подготовку. В интерфейсе есть отмена активной спекуляции через Ctrl+C в состоянии ожидания. Накопленная подготовка не принимается автоматически.',
      sources:[['components/PromptInput/PromptInput.tsx',1730],['services/PromptSuggestion/speculation.ts',411]] },
  ],
};
